// Example to demonstrate without catch blok

#include<iostream>

using namespace std;

int main(){
	try{
		throw 10;
	}
return 0;
}